(function() {
   if (!localStorage.length) {
       adArray = [
        {
            id: "1",
            nameOfService: "education",
            description: "Скидка на курсы немецкого языка",
            createdAt: new Date("2021-03-02T00:00:00"),
            link: "germancourse2021.by",
            vendor: "Germ Teacher",
            photoLink: "https://germanfox.ru/wp-content/uploads/2020/01/german-home.jpg",
            hashTags: ["german", "forIT", "course"],
            discount: "30%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["The best courses you can find", "Nice!"],
        },
        {
            id: "2",
            nameOfService: "shop",
            description: "Товары и услуги #1",
            createdAt: new Date("2021-03-22T00:00:00"),
            link: "corpshop.by",
            vendor: "corpShop",
            photoLink: "https://www.mcgua.com/wp-content/uploads/2019/06/magazin.png",
            hashTags: ["shop", "forIT", "number1"],
            discount: "30%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["The best!", "Nice!"],
        },
        {
            id: "3",
            nameOfService: "shop",
            description: "Товары и услуги #2",
            createdAt: new Date("2021-03-22T00:00:00"),
            link: "corpshop.by",
            vendor: "corpShop",
            photoLink: "https://www.mcgua.com/wp-content/uploads/2019/06/magazin.png",
            hashTags: ["shop", "forIT", "number2"],
            discount: "30%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["The best!", "Nice!"],
        },
        {
            id: "4",
            nameOfService: "shop",
            description: "Товары и услуги #3",
            createdAt: new Date("2021-03-22T00:00:00"),
            link: "corpshop.by",
            vendor: "corpShop",
            photoLink: "https://www.mcgua.com/wp-content/uploads/2019/06/magazin.png",
            hashTags: ["shop", "forIT", "number3"],
            discount: "50%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["The best!", "Nice!"],
        },
        {
            id: "5",
            nameOfService: "shop",
            description: "Товары и услуги #4",
            createdAt: new Date("2021-03-22T00:00:00"),
            link: "corpshop.by",
            vendor: "corpShop",
            photoLink: "https://www.mcgua.com/wp-content/uploads/2019/06/magazin.png",
            hashTags: ["shop", "forIT", "number4"],
            discount: "10%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["The best!", "Nice!"],
        },
        {
            id: "6",
            nameOfService: "shop",
            description: "Товары и услуги #5",
            createdAt: new Date("2021-03-22T00:00:00"),
            link: "corpshop.by",
            vendor: "corpShop",
            photoLink: "https://www.mcgua.com/wp-content/uploads/2019/06/magazin.png",
            hashTags: ["shop", "forIT", "number5"],
            discount: "15%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["The best!", "Nice!"],
        },
        {
            id: "7",
            nameOfService: "repair",
            description: "Окна",
            createdAt: new Date("2021-03-03T00:00:00"),
            link: "windows2021.by",
            vendor: "WindowCompany",
            photoLink: "https://www.evrofasad.by/new_tpl/i/price/01_SALAMANDER.png",
            hashTags: ["windows", "forIT"],
            discount: "50%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 2, 
            reviews: ["The worst windows I ever have"],
        },
        {
            id: "8",
            nameOfService: "repair",
            description: "Окна",
            createdAt: new Date("2021-03-04T00:00:00"),
            link: "GoodWindows2021.by",
            vendor: "GoodWindowCompany",
            photoLink: "https://www.evrofasad.by/new_tpl/i/price/01_SALAMANDER.png",
            hashTags: ["windows", "forIT"],
            discount: "50%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 3, 
            reviews: ["no bad"],
        },
        {
            id: "9",
            nameOfService: "repair",
            description: "Окна",
            createdAt: new Date("2021-03-05T00:00:00"),
            link: "NiceWindows2021.by",
            vendor: "NiceWindowCompany",
            photoLink: "https://www.evrofasad.by/new_tpl/i/price/01_SALAMANDER.png",
            hashTags: ["windows", "forIT"],
            discount: "50%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 4, 
            reviews: ["nice!", "good windows"],
        },
        {
            id: "10",
            nameOfService: "repair",
            description: "Окна",
            createdAt: new Date("2021-03-06T00:00:00"),
            link: "BestWindows2021.by",
            vendor: "BestWindowCompany",
            photoLink: "https://www.evrofasad.by/new_tpl/i/price/01_SALAMANDER.png",
            hashTags: ["windows", "forIT"],
            discount: "50%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["The best windows!"],
        },
        {
            id: "11",
            nameOfService: "repair",
            description: "Двери",
            createdAt: new Date("2021-03-07T00:00:00"),
            link: "worstdoors.by",
            vendor: "WorstDoorsCompany",
            photoLink: "https://virtoni.by/upload/iblock/5b9/emalirovannye_dveri_2.jpg",
            hashTags: ["doors", "forIT", "worst"],
            discount: "100%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 1, 
            reviews: ["its really worst!", "-5"],
        },
        {
            id: "12",
            nameOfService: "repair",
            description: "Двери",
            createdAt: new Date("2021-03-08T00:00:00"),
            link: "nobaddoors.by",
            vendor: "NoBadDoorsCompany",
            photoLink: "https://virtoni.by/upload/iblock/5b9/emalirovannye_dveri_2.jpg",
            hashTags: ["doors", "forIT", "nobad"],
            discount: "70%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 3, 
            reviews: ["No bad"],
        },
        {
            id: "13",
            nameOfService: "repair",
            description: "Двери",
            createdAt: new Date("2021-03-09T00:00:00"),
            link: "gooddoors.by",
            vendor: "GoodDoorsCompany",
            photoLink: "https://virtoni.by/upload/iblock/5b9/emalirovannye_dveri_2.jpg",
            hashTags: ["doors", "forIT", "good"],
            discount: "60%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 4, 
            reviews: ["no bad!"],
        },
        {
            id: "14",
            nameOfService: "repair",
            description: "Двери",
            createdAt: new Date("2021-03-10T00:00:00"),
            link: "nicedoors.by",
            vendor: "NiceDoorsCompany",
            photoLink: "https://virtoni.by/upload/iblock/5b9/emalirovannye_dveri_2.jpg",
            hashTags: ["doors", "forIT", "nice"],
            discount: "50%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["nice!", "its for you!"],
        },
        {
            id: "15",
            nameOfService: "repair",
            description: "Двери",
            createdAt: new Date("2021-03-11T00:00:00"),
            link: "greatdoors.by",
            vendor: "GreatDoorsCompany",
            photoLink: "https://virtoni.by/upload/iblock/5b9/emalirovannye_dveri_2.jpg",
            hashTags: ["doors", "forIT", "great"],
            discount: "10%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["You can't find better"],
        },
        {
            id: "16",
            nameOfService: "shop",
            description: "Ноутбуки",
            createdAt: new Date("2021-03-20T00:00:00"),
            link: "notebooks.by",
            vendor: "NoteCompany",
            photoLink: "https://ert-group.by/%D0%BD%D0%BE%D1%83%D1%82%D0%B1%D1%83%D0%BA%D0%B8.jpg",
            hashTags: ["notebook", "forIT", "device"],
            discount: "30%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["Nice!"],
        },
        {
            id: "17",
            nameOfService: "shop",
            description: "Телефоны",
            createdAt: new Date("2021-03-19T00:00:00"),
            link: "phone.by",
            vendor: "RingCompany",
            photoLink: "https://www.ixbt.com/img/n1/news/2020/4/2/6409301-1568887001_large.jpg",
            hashTags: ["phone", "forIT", "device"],
            discount: "30%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["The best phones you can find", "Nice!"],
        },
        {
            id: "18",
            nameOfService: "education",
            description: "Скидка на курсы японского языка",
            createdAt: new Date("2021-03-22T00:00:00"),
            link: "japancourse2021.by",
            vendor: "Japan Teacher",
            photoLink: "https://cdn22.img.ria.ru/images/130058/95/1300589535_0:99:2000:1233_600x0_80_0_0_49cc5a56fb9ea9aa21d1776df47bc5d1.jpg",
            hashTags: ["japan", "forIT", "course"],
            discount: "30%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["The best courses you can find", "Nice!"],
        },
        {
            id: "19",
            nameOfService: "education",
            description: "Скидка на курсы китайского языка",
            createdAt: new Date("2021-03-22T00:00:00"),
            link: "chinacourse2021.by",
            vendor: "China Teacher",
            photoLink: "https://cdn22.img.ria.ru/images/130058/95/1300589535_0:99:2000:1233_600x0_80_0_0_49cc5a56fb9ea9aa21d1776df47bc5d1.jpg",
            hashTags: ["china", "forIT", "course"],
            discount: "30%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["The best courses you can find", "Nice!"],
        },
        {
            id: "20",
            nameOfService: "education",
            description: "Скидка на курсы испанского языка",
            createdAt: new Date("2021-03-22T00:00:00"),
            link: "spaincourse2021.by",
            vendor: "Spain Teacher",
            photoLink: "https://cdn22.img.ria.ru/images/130058/95/1300589535_0:99:2000:1233_600x0_80_0_0_49cc5a56fb9ea9aa21d1776df47bc5d1.jpg",
            hashTags: ["spain", "forIT", "course"],
            discount: "30%",
            validUntil: new Date("2021-06-01T00:00:00"),
            rating: 5, 
            reviews: ["The best courses you can find", "Nice!"],
        },
    ];
    adArray.forEach(element => {
        localStorage.setItem(element.id, JSON.stringify(element))
    });
   }
}());   
    
